### ISSUE TITLE
Header, bold and italic syntax not rendering. Lists indentation works well though.

### ISSUE THREAD

**Issue by RocketRobC** [gabrielelana/vim-markdown#52]
<img width="167" alt="screen shot 2016-08-14 at 11 41 29 pm" src="https://cloud.githubusercontent.com/assets/12511973/17649428/a9647726-6278-11e6-863a-91f81509192e.png">

I can get these syntax working with other markdown plugins however, your list indentation is the best.

**Comment by gabrielelana** [comment]
Stupid question, are you sure that the plugin is loaded?

You can check with `:scriptnames` or, if you use Vundle, with `:PluginList`

**Comment by RocketRobC** [comment]
I've checked both those and looked at the vim-markdown/ftplugin dir to see which file is being loaded and it appears to be active.

**Comment by gabrielelana** [comment]
@RocketRobC another markdown plugin is interfering? Try to exclude every other plugin but this ad see if something changes

Otherwise, to make sure that the plugin is loaded, can you please post the output of `:echo g:markdown_mapping_switch_status` and `:echo b:current_syntax`?

To make **really** sure that the syntax is loaded:
* Edit `vim-markdown/syntax/markdown.vim` in your load path
* In the last lines change `let b:current_syntax = "markdown"` in something recognizable like `let b:current_syntax = "markdown-xxx"`
* Exit vim
* Open a markdown file
* What's the output of `:echo b:current_syntax`?

If it's "markdown-xxx" the only thing I could think of it's a problem with the color scheme, for that you can try to `:colorscheme default` and see if something changes

**Comment by RocketRobC** [comment]
OK, I've gone through those steps and yes, there was a conflict. All appears to be working well now.  

Thank you for the help.

**Comment by gabrielelana** [comment]
You welcome 😉
